version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autosalon
    ports:
      - "8001:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SECRET_KEY=django-insecure-urv_$^55e2j!hm#=b+9zkddjrzgbklnk3gj-1jdrm)znnr_(do
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0|127.0.0.1
      - POSTGRES_NAME=autosalon
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD_AUTH_METHOD=trust

    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery-worker

  db:
    image: postgres:15.3-alpine
    container_name: autosalon-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234567890

  redis:
    image: redis:7.0.4-alpine
    container_name: autosalon-redis
    hostname: redis
    restart: always

  celery-worker:
    image: "autosalon"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autosalon-celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A autosalon worker -l INFO
    logging:
      options:
        max-size: '500M'
        max-file: '5'
    restart: always
    volumes:
      - .:/app
