version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autosalon
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery-worker

  db:
    image: postgres:15.3-alpine
    container_name: autosalon-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=autosalon
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:7.0.4-alpine
    container_name: autosalon-redis
    hostname: redis
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autosalon-celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DB_URL=postgres://admin1:1234567890@postgres:5432/autosalon
    command: celery -A autosalon worker -l INFO
    logging:
      options:
        max-size: '500M'
        max-file: '5'
    restart: always
    volumes:
      - .:/app
