# Generated by Django 4.2.4 on 2023-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=100, verbose_name='Контактный номер')),
                ('about_us', models.TextField(verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
