# Generated by Django 4.2.4 on 2023-08-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
    ]
