# Generated by Django 4.2.4 on 2023-09-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
