# Generated by Django 4.2.4 on 2023-10-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('engine_volume', models.FloatField(verbose_name='Объём двигателя')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя(л/с)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementCarEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'комплектация',
                'verbose_name_plural': 'комплектации',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_index=True, upload_to='transport', verbose_name='фотографии объявлений')),
            ],
            options={
                'verbose_name': 'фотографии автомобиля',
                'verbose_name_plural': 'фотографии автомобилей',
            },
        ),
        migrations.CreateModel(
            name='BodyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=50, unique=True, verbose_name='кузов')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'кузов',
                'verbose_name_plural': 'кузова',
            },
        ),
        migrations.CreateModel(
            name='BodyTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50, unique=True, verbose_name='тип кузова')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'тип кузова',
                'verbose_name_plural': 'типы кузова',
            },
        ),
        migrations.CreateModel(
            name='BrandCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True, verbose_name='марка')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='цвет')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
            },
        ),
        migrations.CreateModel(
            name='DriveUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_unit', models.CharField(max_length=20, unique=True, verbose_name='привод')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'тип привода',
                'verbose_name_plural': 'типы приводов',
            },
        ),
        migrations.CreateModel(
            name='EngineTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=20, unique=True, verbose_name='тип двигателя')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'тип двигателя',
                'verbose_name_plural': 'типы двигателей',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=64, unique=True, verbose_name='характеристика комплектации')),
            ],
            options={
                'verbose_name': 'характеристика коплектации',
                'verbose_name_plural': 'характеристики комплектации',
            },
        ),
        migrations.CreateModel(
            name='MileageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(unique=True, verbose_name='Пробег')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'пробег',
                'verbose_name_plural': 'пробеги',
            },
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True, verbose_name='модель')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=20, unique=True, verbose_name='коробка передач')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'тип коробки передач',
                'verbose_name_plural': 'типы коробок передач',
            },
        ),
        migrations.CreateModel(
            name='YearOfIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_issue', models.PositiveIntegerField(unique=True, verbose_name='Год выпуска')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'год выпуска',
                'verbose_name_plural': 'года выпуска',
            },
        ),
        migrations.AddConstraint(
            model_name='yearofissuetype',
            constraint=models.CheckConstraint(check=models.Q(('year_of_issue__lte', 2023)), name='year_of_issue__lte'),
        ),
        migrations.AddConstraint(
            model_name='transmissiontype',
            constraint=models.CheckConstraint(check=models.Q(('transmission__length__lte', 20)), name='transmission__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='transmissiontype',
            constraint=models.CheckConstraint(check=models.Q(('transmission__length__gte', 0)), name='transmission__length__gte'),
        ),
        migrations.AddField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='transport.brandcar'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcar',
            constraint=models.CheckConstraint(check=models.Q(('characteristic__length__lte', 64)), name='characteristic__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcar',
            constraint=models.CheckConstraint(check=models.Q(('characteristic__length__gte', 0)), name='characteristic__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='enginetypecar',
            constraint=models.CheckConstraint(check=models.Q(('engine__length__lte', 20)), name='engine__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='enginetypecar',
            constraint=models.CheckConstraint(check=models.Q(('engine__length__gte', 0)), name='engine__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='driveunittype',
            constraint=models.CheckConstraint(check=models.Q(('drive_unit__length__lte', 20)), name='drive_unit__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='driveunittype',
            constraint=models.CheckConstraint(check=models.Q(('drive_unit__length__gte', 0)), name='drive_unit__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='colortype',
            constraint=models.CheckConstraint(check=models.Q(('color__length__lte', 50)), name='color__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='colortype',
            constraint=models.CheckConstraint(check=models.Q(('color__length__gte', 0)), name='color__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='brandcar',
            constraint=models.CheckConstraint(check=models.Q(('brand_name__length__lte', 50)), name='brand_name__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='brandcar',
            constraint=models.CheckConstraint(check=models.Q(('brand_name__length__gte', 0)), name='brand_name__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='bodytypecar',
            constraint=models.CheckConstraint(check=models.Q(('body_type__length__lte', 50)), name='body_type__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='bodytypecar',
            constraint=models.CheckConstraint(check=models.Q(('body_type__length__gte', 0)), name='body_type__length__gte'),
        ),
        migrations.AddField(
            model_name='bodycar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='transport.modelcar'),
        ),
        migrations.AddField(
            model_name='announcementcarimage',
            name='announcement_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transport.announcementcar'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='adjustments_seats_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adjustments_seats_name_announcement', to='transport.equipmentcar', verbose_name='регулировка сидений'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='blind_spot_monitoring_system_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blind_spot_monitoring_system_name_announcement', to='transport.equipmentcar', verbose_name='система контроля слепых зон'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='bluetooth_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bluetooth_name_announcement', to='transport.equipmentcar', verbose_name='bluetooth-система'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='body_kit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body_kit_name_announcement', to='transport.equipmentcar', verbose_name='обвес'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='climate_control_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='climate_control_name_announcement', to='transport.equipmentcar', verbose_name='климат-контроль'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='collision_avoidance_system_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collision_avoidance_system_name_announcement', to='transport.equipmentcar', verbose_name='система избежания столкновений'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='color_salon_car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_salon_car_name_announcement', to='transport.equipmentcar', verbose_name='цвет салона'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='equipment_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_announcement', to='transport.announcementcar', verbose_name='объявление'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='headlights_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='headlights_name_announcement', to='transport.equipmentcar', verbose_name='тип фар'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='heated_seats_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='heated_seats_name_announcement', to='transport.equipmentcar', verbose_name='подогрев сидений'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='lane_departure_warning_system_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lane_departure_warning_system_name_announcement', to='transport.equipmentcar', verbose_name='система предупреждения о сходе с полосы'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='light_sensor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='light_sensor_name_announcement', to='transport.equipmentcar', verbose_name='датчик света'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='parking_sensors_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parking_sensors_name_announcement', to='transport.equipmentcar', verbose_name='датчик парковки'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='rain_sensor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rain_sensor_name_announcement', to='transport.equipmentcar', verbose_name='датчик дождя'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='roof_car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roof_car_name_announcement', to='transport.equipmentcar', verbose_name='характеристики комплектации'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='salon_car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salon_car_name_announcement', to='transport.equipmentcar', verbose_name='тип салона'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='start_stop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_stop_name_announcement', to='transport.equipmentcar', verbose_name='система start-stop'),
        ),
        migrations.AddField(
            model_name='announcementcarequipment',
            name='ventilation_seats_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventilation_seats_name_announcement', to='transport.equipmentcar', verbose_name='вентиляция сидений'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bodycar', verbose_name='кузов'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bodytypecar', verbose_name='тип кузова'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.brandcar', verbose_name='бренд'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_color_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.colortype', verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_drive_unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.driveunittype', verbose_name='тип привода'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.enginetypecar', verbose_name='тип двигателя'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_mileage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.mileagetype', verbose_name='пробег'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.modelcar', verbose_name='модель'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_transmission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.transmissiontype', verbose_name='тип коробки передач'),
        ),
        migrations.AddField(
            model_name='announcementcar',
            name='car_year_of_issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.yearofissuetype', verbose_name='год выпуска'),
        ),
        migrations.AddConstraint(
            model_name='modelcar',
            constraint=models.CheckConstraint(check=models.Q(('model_name__length__lte', 50)), name='model_name__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='modelcar',
            constraint=models.CheckConstraint(check=models.Q(('model_name__length__gte', 0)), name='model_name__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='bodycar',
            constraint=models.CheckConstraint(check=models.Q(('body_name__length__lte', 50)), name='body_name__length__lte'),
        ),
        migrations.AddConstraint(
            model_name='bodycar',
            constraint=models.CheckConstraint(check=models.Q(('body_name__length__gte', 0)), name='body_name__length__gte'),
        ),
        migrations.AddConstraint(
            model_name='announcementcar',
            constraint=models.CheckConstraint(check=models.Q(('engine_volume__gte', 0)), name='engine_volume__ge'),
        ),
    ]
