# Generated by Django 4.2.4 on 2023-09-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcar',
            name='announcement_car_slug',
            field=models.SlugField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcementcar',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.brandcar', verbose_name='бренд'),
        ),
    ]
