# Generated by Django 4.2.4 on 2023-10-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcarequipment',
            name='music_system_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='music_system_name_announcement', to='transport.equipmentcar', verbose_name='Аудиосистема'),
        ),
    ]
