# Generated by Django 4.2.4 on 2023-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_brandcar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcar',
            name='year_of_issue',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
    ]
