# Generated by Django 4.2.4 on 2023-10-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_announcementcarequipment_music_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcar',
            name='car_color_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.colortype', verbose_name='цвет кузова'),
        ),
        migrations.AlterField(
            model_name='announcementcarequipment',
            name='roof_car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roof_car_name_announcement', to='transport.equipmentcar', verbose_name='тип крыши'),
        ),
        migrations.AlterField(
            model_name='announcementcarimage',
            name='announcement_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transport.announcementcar', verbose_name='объявление'),
        ),
    ]
