# Generated by Django 4.2.4 on 2023-10-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_announcementcarimage_announcement_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='transport.modelcar'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='transport.brandcar'),
        ),
    ]
