# Generated by Django 4.2.4 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_announcementcar_announcement_car_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcar',
            name='announcement_car_slug',
            field=models.SlugField(max_length=200),
        ),
    ]
