# Generated by Django 4.2.4 on 2023-08-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_modelcar_year_of_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcar',
            options={'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='modelcar',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
    ]
