# Generated by Django 4.2.4 on 2023-10-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_bodycar_model_alter_modelcar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcarequipment',
            name='heated_seats_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.heatedseatstype', verbose_name='подогрев сидений'),
        ),
    ]
