# Generated by Django 4.2.4 on 2023-08-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_brandcar_options_alter_modelcar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcar',
            options={'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
    ]
