# Generated by Django 4.2.4 on 2023-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_modelcar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcar',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
