# Generated by Django 4.2.4 on 2023-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_modelcar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcar',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
