# Generated by Django 4.2.4 on 2023-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_modelcar_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcar',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
