# Generated by Django 4.2.4 on 2023-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_modelcar_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcar',
            name='body',
            field=models.CharField(default=False, max_length=20, verbose_name='Кузов'),
        ),
    ]
