# Generated by Django 4.2.4 on 2023-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_alter_modelcar_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcar',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='body',
            field=models.CharField(max_length=50, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
