# Generated by Django 4.2.4 on 2023-09-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_brandcar_slug_alter_modelcar_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcar',
            old_name='brand_car',
            new_name='brand',
        ),
    ]
