# Generated by Django 4.2.4 on 2023-09-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_rename_brand_car_modelcar_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcar',
            name='state',
        ),
        migrations.AddField(
            model_name='modelcar',
            name='equipment',
            field=models.TextField(default=False, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
    ]
