# Generated by Django 4.2.4 on 2023-09-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_remove_modelcar_state_modelcar_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcar',
            name='equipment',
            field=models.TextField(verbose_name='Комплектация'),
        ),
    ]
