# Generated by Django 4.2.4 on 2023-09-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_alter_modelcar_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50, verbose_name='Кузов')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'кузов',
                'verbose_name_plural': 'кузова',
            },
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='body',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='color',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='drive_unit',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='engine_volume',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='price',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='modelcar',
            name='year_of_issue',
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('year_of_issue', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('engine_volume', models.FloatField(verbose_name='Объём двигателя')),
                ('engine_type', models.CharField(max_length=20, verbose_name='Тип двигателя')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя(л/с)')),
                ('transmission', models.CharField(max_length=20, verbose_name='Коробка передач')),
                ('drive_unit', models.CharField(max_length=20, verbose_name='Привод')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('equipment', models.TextField(verbose_name='Комплектация')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bodycar')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.AddField(
            model_name='bodycar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.modelcar'),
        ),
    ]
