# Generated by Django 4.2.4 on 2023-09-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_bodycar_remove_modelcar_body_remove_modelcar_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_body', models.CharField(max_length=50, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'тип кузова',
                'verbose_name_plural': 'типы кузова',
            },
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
            },
        ),
        migrations.CreateModel(
            name='DriveUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_unit', models.CharField(max_length=20, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'тип привода',
                'verbose_name_plural': 'типы приводов',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=20, verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'тип двигателя',
                'verbose_name_plural': 'типы двигателей',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=20, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'коробка передач',
                'verbose_name_plural': 'коробки передач',
            },
        ),
        migrations.RemoveField(
            model_name='description',
            name='color',
        ),
        migrations.RemoveField(
            model_name='description',
            name='drive_unit',
        ),
        migrations.RemoveField(
            model_name='description',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='description',
            name='transmission',
        ),
        migrations.AlterField(
            model_name='bodycar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bodies', to='transport.modelcar'),
        ),
        migrations.AlterField(
            model_name='description',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptions', to='transport.bodycar'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models', to='transport.brandcar'),
        ),
        migrations.CreateModel(
            name='AnnouncementCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bodycar')),
                ('car_body_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bodytypecar')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.brandcar')),
                ('car_color_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.colortype')),
                ('car_descr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.description')),
                ('car_drive_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.driveunittype')),
                ('car_engine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.enginetype')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.modelcar')),
                ('car_transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.transmissiontype')),
            ],
        ),
    ]
